name: build

on:
  push:
  pull_request:

jobs:

  test:
    name: Test
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          components: rustfmt, clippy, llvm-tools-preview, rust-src
          profile: default

      - uses: actions-rs/cargo@v1
        with:
          command: test
